

## Nodejs frontend项目配置
# 运行默认端口
export QLCHAT_NODEJS_FRONTEND_SERVER_PORT='5000'

# 接口地址前缀
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_BASEAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_APPAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_WEIBOAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_WECHATAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_ADMINAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_ACTIVITYAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_WEAPPAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_COUPONAPI=''
export QLCHAT_NODEJS_FRONTEND_API_PREFIX_SHAREFRONTAPI=''

# 接口签名
export QLCHAT_NODEJS_FRONTEND_API_KEY_BASEAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_APPAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_WEIBOAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_WECHATAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_ADMINAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_ACTIVITYAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_WEAPPAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_COUPONAPI=''
export QLCHAT_NODEJS_FRONTEND_API_KEY_SHAREFRONTAPI=''

# 请求超时
export QLCHAT_NODEJS_FRONTEND_REQUEST_TIMEOUT='7000'

# 登录sessoin相关redis配置
export QLCHAT_NODEJS_FRONTEND_REDIS_PORT=''
export QLCHAT_NODEJS_FRONTEND_REDIS_HOST=''
export QLCHAT_NODEJS_FRONTEND_REIDS_NOREADYCHECK=true
export QLCHAT_NODEJS_FRONTEND_REIDS_PASSWORD=''
export QLCHAT_NODEJS_FRONTEND_REIDS_EXPIRE=86400

# 微信配置相关redis(主服务redis)配置
export QLCHAT_NODEJS_FRONTEND_TOKENREDIS_PORT=''
export QLCHAT_NODEJS_FRONTEND_TOKENREDIS_HOST=''
export QLCHAT_NODEJS_FRONTEND_TOKENREDIS_NOREADYCHECK=false
export QLCHAT_NODEJS_FRONTEND_TOKENREDIS_PASSWORD=''

# 静态服务相关redis配置
export QLCHAT_NODEJS_FRONTEND_STATICREDIS_PORT=''
export QLCHAT_NODEJS_FRONTEND_STATICREDIS_HOST=''
export QLCHAT_NODEJS_FRONTEND_STATICREDIS_NOREADYCHECK=false
export QLCHAT_NODEJS_FRONTEND_STATICREDIS_PASSWORD=''

# lru本地缓存配置
export QLCHAT_NODEJS_FRONTEND_LRU_MAX=2
export QLCHAT_NODEJS_FRONTEND_LRU_MAX_AGE=2

# 微信开放平台appid（用于二维码登录二维码）
export QLCHAT_NODEJS_FRONTEND_WX_OPEN_APPID=''

# 微博应用id
export QLCHAT_NODEJS_FRONTEND_WEIBO_CLIENT_ID=''

# 日志采集配置
export QLCHAT_NODEJS_FRONTEND_COLLECTJS=''
export QLCHAT_NODEJS_FRONTEND_SPACOLLECTJS=''
export QLCHAT_NODEJS_FRONTEND_COLLECT_APIPREFIX=''
export QLCHAT_NODEJS_FRONTEND_WEBSOCKET_URL=''
