var lo = require('lodash'),
    resProcessor = require('../../components/res-processor/res-processor'),
    proxy = require('../../components/proxy/proxy'),
    wxAuth = require('../../middleware/auth/1.0.0/wx-auth'),
    appAuth = require('../../middleware/auth/1.0.0/app-auth'),
	clientParams = require('../../middleware/client-params/client-params'),
    conf = require('../../conf'),
    requestProcess = require('../../middleware/request-process/request-process');


module.exports = [
    ['GET', '/api/wechat/coral/getAccountData', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getAccountData, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/shopCouseList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getPersonPartyCourseList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getRankList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getRankList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getRecommendList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getRecommendList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getBannerList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getBannerList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getMyShareList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyShareList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getMyProfitRecord', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyProfitRecord, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getMyIdentity', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyIdentity, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getCoursetagList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getCoursetagList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getQlShareKey', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.share.getQlShareKey, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getIndexFloatBox', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getIndexFloatBox, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getSubjectCourseList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getSubjectCourseList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getSubjectList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getSubjectList, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getSubject', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getSubject, conf.baseApi.secret)],
    ['GET', '/api/wechat/coral/getIconList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getIconList, conf.baseApi.secret)],
    ['POST','/api/wechat/coral/getWithdrawtList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getWithdrawtList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/personWithdraw', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.personWithdraw, conf.baseApi.secret)],
	['POST','/api/wechat/coral/personReWithdraw', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.personReWithdraw, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getMyCommunityList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyCommunityList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getMyTemporaryRefCount', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyTemporaryRefCount, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getMyCommunityCount', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyCommunityCount, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getMyTemporaryRefList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyTemporaryRefList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/joinCollection', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.joinCollection, conf.baseApi.secret)],
	['POST','/api/wechat/coral/updateOrderData', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.updateOrderData, conf.baseApi.secret)],
	['POST','/api/wechat/coral/bindUserRef', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.bindUserRef, conf.baseApi.secret)],
	['POST','/api/wechat/coral/achievementList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.achievementList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/achievementDetailList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.achievementDetailList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/access', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.access, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getMyPersonMonthAchievement', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyPersonMonthAchievement, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getMyCacheParent', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getMyCacheParent, conf.baseApi.secret)],
	['POST','/api/wechat/coral/updateCacheParent', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.updateCacheParent, conf.baseApi.secret)],
	['POST','/api/wechat/coral/isHideReferrer', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.isHideReferrer, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getExcellentRankList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getExcellentRankList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getCourseMaterial', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getCourseMaterial, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getCoralProfitConfig', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getCoralProfitConfig, conf.baseApi.secret)],
	['POST','/api/wechat/coral/personCourseOnSaleInfo', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.personCourseOnSaleInfo, conf.baseApi.secret)],
	['GET','/api/wechat/coral/getShareCutCourseInfo', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getShareCutCourseInfo, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getImgUrlConfig', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getImgUrlConfig, conf.baseApi.secret)],
	['POST','/api/wechat/coral/getPersonCourseInfo', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getPersonCourseInfo, conf.baseApi.secret)],

	//珊瑚计划授权
	['GET','/api/wechat/coral/getReserveCourseList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getReserveCourseList, conf.baseApi.secret)],
	['GET','/api/wechat/coral/getLivePersonPartyCourseList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getLivePersonPartyCourseList, conf.baseApi.secret)],
	['POST','/api/wechat/coral/applyPush', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.applyPush, conf.baseApi.secret)],
	
	['POST','/api/wechat/coral/getFocusAppId', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getFocusAppId, conf.baseApi.secret)],
	//getBackgroundUrlList
	['GET','/api/wechat/coral/getBackgroundUrlList', clientParams(), appAuth(), wxAuth(), requestProcess(conf.baseApi.coral.getBackgroundUrlList, conf.baseApi.secret)],
];
